# Generated by Django 3.0.8 on 2020-08-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard_name', models.CharField(blank=True, max_length=128, verbose_name='Назва материнської плати:')),
                ('motherboard_price', models.IntegerField(default=0, verbose_name='Ціна материнської плати:')),
                ('motherboard_image', models.ImageField(blank=True, upload_to='static/media/motherboard_image', verbose_name='Фото материнської плати')),
                ('motherboard_producer', models.CharField(blank=True, max_length=32, verbose_name='Виробник материнської плати:')),
                ('motherboard_type', models.CharField(blank=True, max_length=64, verbose_name='Тип розєму:')),
                ('motherboard_chip_set', models.CharField(blank=True, max_length=24, verbose_name='Чипсет (Північний міст):')),
                ('motherboard_memory_support', models.CharField(blank=True, max_length=24, verbose_name='Підтримка памяті:')),
                ('motherboard_form_factor', models.CharField(blank=True, max_length=24, verbose_name='Форм фактор:')),
                ('motherboard_number_of_memory_slots', models.SmallIntegerField(verbose_name='Кількість слотів памяті')),
                ('motherboard_processors_support', models.CharField(blank=True, max_length=128, verbose_name='Підтрика процесорів:')),
                ('motherboard_maximum_amount_of_RAM', models.CharField(blank=True, max_length=128, verbose_name='Назва материнської плати:')),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_name', models.CharField(blank=True, max_length=128, verbose_name='Сімейство процесора:')),
                ('processor_price', models.IntegerField(default=0, verbose_name='Ціна процесора:')),
                ('processor_image', models.ImageField(blank=True, upload_to='static/media/processor_image', verbose_name='Фото процесора:')),
                ('processor_producer', models.CharField(blank=True, max_length=32, verbose_name='Виробник процесора:')),
                ('processor_socket', models.CharField(blank=True, max_length=32, verbose_name='Тип сокета:')),
                ('processor_number_of_cores', models.SmallIntegerField(verbose_name='Кількість ядер:')),
                ('processor_integrated_graphics', models.CharField(blank=True, max_length=64, verbose_name='Інтегрована графіка:')),
                ('processor_frequency', models.CharField(blank=True, max_length=24, verbose_name='Внутрішня частота:')),
                ('processor_max_frequency', models.CharField(blank=True, max_length=24, verbose_name='Максимальна частота:')),
                ('processor_number_of_thread', models.SmallIntegerField(verbose_name='Кількість потоків:')),
                ('processor_number_of_memory_channels', models.SmallIntegerField(verbose_name='Кількість каналів памті:')),
                ('processor_type_of_memory', models.CharField(blank=True, max_length=24, verbose_name='Тип памті процесора:')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAM_name', models.CharField(blank=True, max_length=128, verbose_name='Назва оперативної памяті:')),
                ('RAM_price', models.IntegerField(default=0, verbose_name='Ціна оперативної памяті:')),
                ('RAM_image', models.ImageField(blank=True, upload_to='static/media/RAM_image', verbose_name="Фото оперативної пам'яті")),
                ('RAM_amount_of_memory', models.CharField(blank=True, max_length=24, verbose_name='Обсяг памяті:')),
                ('RAM_type_of_memory', models.CharField(blank=True, max_length=24, verbose_name='Тип памяті:')),
                ('RAM_supply_voltage', models.CharField(blank=True, max_length=24, verbose_name='Напруга живлення:')),
                ('RAM_memory_frequency', models.CharField(blank=True, max_length=24, verbose_name='Частота памяті:')),
                ('RAM_effective_bandwidth', models.CharField(blank=True, max_length=24, verbose_name='Ефективна пропускна здатність:')),
                ('RAM_number_of_slats', models.SmallIntegerField(default=0, verbose_name='Кількість планок:')),
                ('RAM_producer', models.CharField(blank=True, max_length=32, verbose_name='Виробник оперативної памяті:')),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSD_name', models.CharField(blank=True, max_length=128, verbose_name='Назва SSD диска:')),
                ('SSD_price', models.IntegerField(default=0, verbose_name='Ціна SSD диска:')),
                ('SSD_image', models.ImageField(blank=True, upload_to='static/media/SSD_image', verbose_name='Фото ssd накопичувача')),
                ('SSD_amount_of_memory', models.CharField(blank=True, max_length=24, verbose_name='Обсяг памяті:')),
                ('SSD_reading_speed', models.CharField(blank=True, max_length=24, verbose_name='Швидкість читання:')),
                ('SSD_recording_speed', models.CharField(blank=True, max_length=24, verbose_name='Швидкість запису:')),
                ('SSD_energy_consumption', models.CharField(blank=True, max_length=68, verbose_name='Енергоспоживання:')),
                ('SSD_interface', models.CharField(blank=True, max_length=24, verbose_name='Інтерфейс:')),
                ('SSD_type_of_memory_elements', models.CharField(blank=True, max_length=24, verbose_name='Тип елементів памяті:')),
                ('SSD_producer', models.CharField(blank=True, max_length=32, verbose_name='Виробник SSD диска:')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_card_name', models.CharField(blank=True, max_length=128, verbose_name='Сімейство відеокатри:')),
                ('video_card_graphics_chip', models.CharField(blank=True, max_length=128, verbose_name='Сімейство відеокатри:')),
                ('video_card_image', models.ImageField(blank=True, upload_to='static/media/video_card_image', verbose_name='Фото відеокарти')),
                ('video_card_price', models.IntegerField(default=0, verbose_name='Ціна відеокатри:')),
                ('video_card_producer', models.CharField(blank=True, max_length=32, verbose_name='Виробник відеокатри:')),
                ('video_card_cooling_system', models.CharField(blank=True, max_length=64, verbose_name='Система охолодження :')),
                ('video_card_type_of_memory', models.CharField(blank=True, max_length=24, verbose_name='Тип памті відеокатри:')),
                ('video_card_amount_of_memory', models.CharField(blank=True, max_length=24, verbose_name='Обсяг памяті відеокатри:')),
                ('video_card_bit_memory_bus', models.CharField(blank=True, max_length=24, verbose_name='Розрядність шини памяті')),
                ('video_card_minimum_required_power', models.CharField(blank=True, max_length=24, verbose_name='Мінімально необхідна потужність БЖ')),
                ('video_card_interface', models.CharField(blank=True, max_length=32, verbose_name='Інтерфейс')),
                ('video_card_maximum_supported_resolution', models.CharField(blank=True, max_length=24, verbose_name='Максимально підтримувана роздільна здатність:')),
            ],
        ),
    ]
