# Generated by Django 3.0.8 on 2020-08-27 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='products.Motherboard')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='products.Processor')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ram', to='products.RAM')),
                ('ssd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssd', to='products.SSD')),
                ('video_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videocard', to='products.VideoCard')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
